### ISSUE TITLE
Package name: wasmrrr or wasmr?

### ISSUE THREAD

**Issue by syrusakbary** [dirkschumacher/wasmrrr#3]
Hi,

In the README the package is mentioned as `dirkschumacher/wasmr`, however the project url is `dirkschumacher/wasmrrr`.

It would be a good idea to standardize into only one name (rename the repo, or fix the README)

**Comment by dirkschumacher** [comment]
Yeah that is a good idea :) I thought the three `rrr` is just confusing so I changed the package name in the code.

Currently working on importing functions from R - almost there I think.

**Comment by dirkschumacher** [comment]
@syrusakbary, @Hywan can I ask you a question regarding the api?

I think I can best ask the question using an example:
Say I use `wasmer_import_func_new` together with the trampoline set of functions to create a new import function to add two `doubles`. Is it possible to define a C function using a `void* data` pointer instead of two parameters `double a, double b`? If yes, how can I access the values in `data`. The reason is that I only know about the function signature at runtime in R, so I have to use a generic C function.

My ideal function signature would look like this :)
```C
double add(wasmer_instance_context_t *ctx, wasmer_value* data) { ... }
```

Thanks in advance
